run:
  timeout: 2m
  tests: true

  build-tags:
    - embed

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gocyclo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
