#!/usr/bin/env bash

# Generates index files for each individual file category and an index for all categories

ALL_INDEX=./index_all.yar
LW_INDEX=./lw_index.yar
YR_INDEX=./yr_index.yar

LW_DIR=./lw-yara
YR_DIR=./yara-rules

LW_OG_INDEX=./lw-yara/lw-rules_index.yar
YR_OG_INDEX=./yara-rules/index.yar

verify_deps_exist() {
    echo "[*] Verifying dependencies are installed..."
    if [[ -d "$LW_DIR" && -f "$LW_OG_INDEX" ]] && [[ -d "$YR_DIR" && -f "$YR_OG_INDEX" ]]; then
        echo "[+] All dependencies are present."
    else
        echo "[!] Missing dependencies. Make sure the submodules have been downloaded properly!"
    fi
}

remove_files_if_exists() {
    echo "[*] Removing old index files..."
    if [ -f $ALL_INDEX ]; then
        rm $ALL_INDEX
    fi

    if [ -f $LW_INDEX ]; then
        rm $LW_INDEX
    fi

    if [ -f $YR_INDEX ]; then
        rm $YR_INDEX
    fi
}

echo_header_to_file() {
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n\n" > $LW_INDEX
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n\n" > $YR_INDEX
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n\n" > $ALL_INDEX
}

add_yara_rules_to_index_files() {
    echo "include \"$LW_OG_INDEX\"" >> $LW_INDEX
    echo "include \"$YR_OG_INDEX\"" >> $YR_INDEX
    ls -fA | grep -iE "*\.yar" | grep -v "index_all.yar" | sort | awk '{print "include \"" $0 "\""}' >> $ALL_INDEX
    
    echo "[+] Yara rules have been added to the new index files."
}

verify_deps_exist
remove_files_if_exists
echo_header_to_file
add_yara_rules_to_index_files

