/*
Generated by wellatleastitried
2025-10-01 16:53:51
*/
include "./media/avi.yar"
include "./media/dmg.yar"
include "./media/gif.yar"
include "./media/img.yar"
include "./media/iso.yar"
include "./media/jpeg.yar"
include "./media/m4a.yar"
include "./media/mkv.yar"
include "./media/mov.yar"
include "./media/mp3.yar"
include "./media/mp4.yar"
include "./media/png.yar"
include "./media/svg.yar"
include "./media/vmdk.yar"
include "./media/webm.yar"
