/*
Generated by wellatleastitried
2025-10-01 16:53:51
*/
include "./binaries/apk.yar"
include "./binaries/class.yar"
include "./binaries/deb.yar"
include "./binaries/dll.yar"
include "./binaries/elf.yar"
include "./binaries/exe.yar"
include "./binaries/mach-o.yar"
include "./binaries/msi.yar"
include "./binaries/obj.yar"
include "./binaries/o.yar"
include "./binaries/pe.yar"
include "./binaries/so.yar"
