/*
Generated by wellatleastitried
2025-10-01 16:53:51
*/
include "./documents/docx.yar"
include "./documents/doc.yar"
include "./documents/pdf.yar"
include "./documents/pptx.yar"
include "./documents/ppt.yar"
include "./documents/xlsx.yar"
include "./documents/xls.yar"
