/*
Generated by wellatleastitried
2025-10-01 16:53:51
*/
include "./misc/7z.yar"
include "./misc/bak.yar"
include "./misc/gz.yar"
include "./misc/NO_FILE_EXTENSTION.yar"
include "./misc/tar.yar"
include "./misc/ttf.yar"
include "./misc/xz.yar"
include "./misc/zip.yar"
