#!/usr/bin/env bash

# Generates index files for each individual file category and an index for all categories

BINARIES=./binaries
CODE=./code
DOCS=./documents
MEDIA=./media
MISC=./misc
TEXT=./text

INDEX_ALL=./index_all.yar
INDEX_BIN=./index_binaries.yar
INDEX_CODE=./index_code.yar
INDEX_DOCS=./index_documents.yar
INDEX_MEDIA=./index_media.yar
INDEX_MISC=./index_misc.yar
INDEX_TEXT=./index_text.yar

remove_files_if_exists() {
    if [ -f $INDEX_ALL ]; then
        rm $INDEX_ALL
    fi

    if [ -f $INDEX_BIN ]; then
        rm $INDEX_BIN
    fi

    if [ -f $INDEX_CODE ]; then
        rm $INDEX_CODE
    fi

    if [ -f $INDEX_DOCS ]; then
        rm $INDEX_DOCS
    fi

    if [ -f $INDEX_MEDIA ]; then
        rm $INDEX_MEDIA
    fi

    if [ -f $INDEX_MISC ]; then
        rm $INDEX_MISC
    fi

    if [ -f $INDEX_TEXT ]; then
        rm $INDEX_TEXT
    fi
}

echo_header_to_file() {
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_ALL
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_BIN
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_CODE
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_DOCS
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_MEDIA
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_MISC
    printf "/*\nGenerated by wellatleastitried\n$(date +"%Y-%m-%d %H:%M:%S")\n*/\n" > $INDEX_TEXT
}

add_yara_rules_to_index_files() {
    ls -fA $BINARIES | grep -iE "*.yar" | sort | awk '{print "include \"" "./binaries/" $0 "\""}' >> $INDEX_BIN
    ls -fA $CODE | grep -iE "*.yar" | sort | awk '{print "include \"" "./code/" $0 "\""}' >> $INDEX_CODE
    ls -fA $DOCS | grep -iE "*.yar" | sort | awk '{print "include \"" "./documents/" $0 "\""}' >> $INDEX_DOCS
    ls -fA $MEDIA | grep -iE "*.yar" | sort | awk '{print "include \"" "./media/" $0 "\""}' >> $INDEX_MEDIA
    ls -fA $MISC | grep -iE "*.yar" | sort | awk '{print "include \"" "./misc/" $0 "\""}' >> $INDEX_MISC
    ls -fA $TEXT | grep -iE "*.yar" | sort | awk '{print "include \"" "./text/" $0 "\""}' >> $INDEX_TEXT
    ls -fA | grep -iE "*.yar" | grep -v "index_all.yar" | sort | awk '{print "include \"" $0 "\""}' >> $INDEX_ALL
}

remove_files_if_exists
echo_header_to_file
add_yara_rules_to_index_files
