name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y just yara libyara-dev

      - name: Install linters
        run: just dev-setup

      - name: Run tests
        run: just test

